### ISSUE TITLE
regtime.exe is 16 bit executable, can there be a 32 bit version created?

### ISSUE THREAD

**Issue by jsolderitsch** [keydet89/Tools#3]
I am running Eric Zimmerman's KAPE suite. A timeline module was created for it and it wants to run regtime.exe.

My 64-bit Windows 10 environment can't execute regtime.exe because it is flagged as a 16 bit program.

Would it be possible to create a version than can run within Windows 10 64 bit?

**Comment by keydet89** [comment]
I use that program on 64-bit Windows 10 and do not get the error; regtime.exe is not 16-bit, it's 32-bit. 

Can you share the error message you're receiving? 

Thanks.

**Comment by jsolderitsch** [comment]
Thanks for responding so quickly. I think my downloads of some .exe files from github were done incorrectly. The file sizes were suspiciously large. I took better care in downloading just now and the file sizes were much smaller than what I was seeing before. I ran the same sequence that failed previously and it now completes.
